tags:
  - name: users
    description: users API

paths:
  /sms:
    post:
      summary: Send SMS messages
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                messages:
                  type: array
                  items:
                    $ref: '#/definitions/Message'
      responses:
        200:
          description: Successfully sent SMS messages
          content:
            application/json:
              schema:
                $ref: '#/definitions/MessageResponse'
        503:
          description: Failed to send SMS messages
          content:
            application/json:
              schema:
                $ref: '#/definitions/MessageResponse'

definitions:
  Message:
    type: object
    properties:
      phoneNumber:
        type: string
      message:
        type: string
  MessageResponse:
    type: object
    properties:
      totalMessages:
        type: integer
      sent:
        type: integer
      unsent:
        type: integer
      storedInBuffer:
        type: integer

schemes:
  - http
